#!/usr/bin/env bash

cabal -v0 new-run hask-oracle -- --eiffel-path ../expression/expression/EIFGENs/expression/W_code/expression --oracle-path ../expression/expression/oracle --at-file-dir ../expression/expression/
